// Sidebar
export const SIDEBAR_VISIBILITY_TOGGLE = "SIDEBAR_VISIBILITY_TOGGLE";
export const SIDEBAR_VISIBILITY_SHOW = "SIDEBAR_VISIBILITY_SHOW";
export const SIDEBAR_VISIBILITY_HIDE = "SIDEBAR_VISIBILITY_HIDE";
export const SIDEBAR_STICKY_TOGGLE = "SIDEBAR_STICKY_TOGGLE";
export const SIDEBAR_STICKY_ENABLE = "SIDEBAR_STICKY_ENABLE";
export const SIDEBAR_STICKY_DISABLE = "SIDEBAR_STICKY_DISABLE";

// Layout
export const LAYOUT_BOXED_TOGGLE = "LAYOUT_BOXED_TOGGLE";
export const LAYOUT_BOXED_ENABLE = "LAYOUT_BOXED_ENABLE";
export const LAYOUT_BOXED_DISABLE = "LAYOUT_BOXED_DISABLE";

// Theme
export const THEME_TOGGLE = "THEME_TOGGLE";

// token & login
export const TOKEN_INFO = "TOKEN_INFO";
export const USER_LOGIN_INFO = "USER_LOGIN_INFO";

// group
export const GET_LIST_GROUP = "GET_LIST_GROUP";
export const GET_LIST_GROUP_SELECTED_ROWS = "GET_LIST_GROUP_SELECTED_ROWS";
//user
export const GET_LIST_USER = "GET_LIST_USER";
export const GET_LIST_USER_SELECTED_ROWS = "GET_LIST_USER_SELECTED_ROWS";
//film
export const GET_LIST_FILM = "GET_LIST_FILM";
//schedule
export const GET_LIST_SCHEDULE = "GET_LIST_SCHEDULE";
export const GET_LIST_SCHEDULE_SELECTED_ROWS = "GET_LIST_SCHEDULE_SELECTED_ROWS";
//ticket
export const GET_LIST_TICKET = "GET_LIST_TICKET";
